security:
  basic:
    enabled: false
management:
  security:
    enabled: false
spring: 
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: email@gmail.com
    password: password
    protocol: smtp
    tls: true
    properties.mail.smtp: 
            auth: true
            starttls.enable: true
            ssl.trust: smtp.gmail.com

      
        
---   
spring:
  profiles: dev
  data:
    mongodb:
      database: user_detail
      host: localhost
      port: 27017
      
---     
spring:
  profiles: prod
  data:
    mongodb:
      #uri: mongodb://user:password@ds113282.mlab.com:13282/CloudFoundry_nqefc3jg_m7oje6p5
      uri: mongodb://awasthi:awasthi@mongodb/hynishdb
